### PR TITLE
convert hyphenated-words to camelCase ref #226

### LINKED ISSUE #226: Name of generated case class of properties/fields when name contains '-'
If name of element has '-' characted in its content scalaxb generates case class with u45.

For example,  
This is part of XSD schema:

```
   <xs:element name="entity-interface">
      <xs:complexType>
        <xs:sequence>
          <xs:element type="xs:string" name="path"/>
        </xs:sequence>
      </xs:complexType>
   </xs:element>
```

and scala will generate this case class:

```
 case class Entityu45interface(path: String)
```

Scalaxb should generate case class with name EntityInterface instead of Entityu45Interface or should have switch to generate class without u45 at least. Same happens for properties names.

### PR DESCRIPTION
**Pull request by oscar-broman**
Fixes #226

### CODE REVIEW

**Comment by oscar-broman** [comment]
A better solution would be a `compiler.Config` option to provide a custom version of `identifier`. The limit of 22 arguments has been hit, however, so it requires some restructuring.

**Comment by eed3si9n** [comment]
Could you add a test case in https://github.com/eed3si9n/scalaxb/blob/master/integration/src/test/resources/general.xsd and https://github.com/eed3si9n/scalaxb/blob/master/integration/src/test/resources/GeneralUsage.scala with a complex type with element name `foo-bar` and `fooBar` to make sure they don't collide?

**Comment by oscar-broman** [comment]
I believe they would collide. It's probably best not to change default behavior, so an option to trigger this behavior should be instated.

Do you have any suggestions as to how such an option would be added? The limit is reached for the `Config` class.

**Comment by liff** [comment]
Assuming it's an acceptable way to do it [this commit](https://github.com/liff/scalaxb/commit/ad348055a1be59f64a64cbc12799ae8b0606509b) should solve the 21 parameter limit.

Should I prepare a separate PR from it?

**Comment by eed3si9n** [comment]
Finally got around to turning configuration into a sequence of case classes. See #342

**Comment by hosamaly** [comment]
This should now be fixed by #461.

**Comment by eed3si9n** [comment]
I am closing this due to inactivity.

**Pull request closed without merging**
