### PR TITLE
Some new features and bug fixes

### PR DESCRIPTION
**Pull request by anatoliykmetyuk**
We with @AndreVanDelft are working with [OpenOffice schemata](http://www.ecma-international.org/publications/standards/Ecma-376.htm), which is the format for MS Office files, using ScalaXB. While on this task, we encountered some bugs and needed some new features. By now, we have polished our changes and hope that ScalaXB team will find them useful.

Below, there's a brief summary of our changes.

# Features
5 features in total are added:

- Mutable binding classes
- Automatic resolution of `xsd:any`
- Visitor
- Automatic package names generation based on the namespace URI
- Deployment script

## Mutable binding classes
It is reasonable to want to modify the bound model. This features enables you to choose whether you want to generate immutable or mutable classes. By adding the `--mutable` flag:

- All the relevant `vals` become `vars`
- `VarArg` config entry is removed, since it is not possible to reassign to vararg
- Attributes get setters

[Relevant test](https://github.com/AndreVanDelft/scalaxb/commit/1b4e6e7784cceed843c3579477e97e39c2dfab62)

### Relevant commits
- [Basic support](https://github.com/AndreVanDelft/scalaxb/commit/162d711ae1f66a2375bb97459e0374799ed27854)
- [VarArg removal](https://github.com/AndreVanDelft/scalaxb/commit/bfe7d686821bf673177d772b80f74d47fd896539)
- [Attribute setters](https://github.com/AndreVanDelft/scalaxb/commit/6d3a9d760e3754db7db7d4de4cb9fe9f70cc8bcf)

## Automatic resolution of xsd:any
Consider the following snippet from `dml-main.xsd`, which is a part of OpenOffice schemata:

```xml
  <xsd:complexType name="CT_GraphicalObjectData">
    <xsd:sequence>
      <xsd:any minOccurs="0" maxOccurs="unbounded" processContents="strict"/>
    </xsd:sequence>
    <xsd:attribute name="uri" type="xsd:token" use="required"/>
  </xsd:complexType>
```

In a `pptx` presentation slide, a XML tree that represents a table goes in place of `xsd:any`, for example:

```xml
<a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/table">
  <a:tbl>
  ...
  </a:tbl>
</a:graphicData>
```
`a:graphicData` is `CT_GraphicalObjectData`.
Apparently, not only the `CT_Table` can be used there, hence `xsd:any`, but often the `CT_Table`, or `a:tbl` is of interest.

The problem is, ScalaXB stores `xsd:any` as bare `scala.xml.Elem`, wrapped into `scalaxb.DataRecord[Any]`. Perhaps this is because `xsd:any` doesn't carry any type information, so ScalaXB doesn't know what to bind the element to.

However, there is a way to know for sure that `<a:tbl>` is a `CT_Table`, since it is declared in the schema:

```xml
  <xsd:element name="tbl" type="CT_Table"/>
```

We have made a system to do such a resolution when parsing `scalaxb.DataRecord[Any]`, when possible. Previously, `DataRecord[Any]` was able to bind only the standard types declared in the `fromAny` method of `scalaxb.scala.template`. Now, we have a list of schema-specific bindable elements in the protocol file, and we redirect the `fromAny` method to the protocol whenever it runs out of options, so that schema-specific bindings can be made.

Here is an abstract from the protocol generated for the OpenOffice schemata featuring `CT_Table` resolution:

```scala
def fromAnySchemaType(elem: scala.xml.Elem): scalaxb.DataRecord[Any] = {
	import scalaxb.{Helper, DataRecord, fromXML}
	
	val ns = Helper.nullOrEmpty(elem.scope.getURI(elem.prefix))
	val key = Some(elem.label)
	val (xsns, xstype) = Helper.instanceType(elem)
	
	(key, ns) match {
		// Many other entries here, omitted...
		case (Some("tbl"), Some("http://schemas.openxmlformats.org/drawingml/2006/main") | None) => DataRecord(ns, key, xsns, xstype, fromXML[schemas.openxmlformats.org.drawingml.n2006.main.CT_Table](elem))
		// Other entries...
		case _ => DataRecord(ns, key, xsns, xstype, elem)
	}
}
```

On the line 10 of the above code, the system will look at the label and the namespace of the unknown element. If it is a table, it will be bound to `CT_Table`. If the function can't determine the type of the element based on the label and the namespace, it will fall back to the standard behaviour on line 12 - i.e. store the element as `scala.xml.Elem`.

Note: in order to make `scalaxb.scala` see a function in the `protocol.scala`, we made `scalaxb.scala.template` to support placeholders. The protocol package is specified as `#{protocolPackage}` there, and this placeholder is substituted at generation time.

[Relevant tests](https://github.com/AndreVanDelft/scalaxb/commit/f3ac2374b33a8c1ecd459ac36e61e3e4df255deb)

[Relevant commits](https://github.com/AndreVanDelft/scalaxb/compare/0a3aa4d3058f20416617cacad19a05ac5c56b774...0db91988cc82e53573e9bbb55467b65ff2f9b89a)

## Visitor
The ScalaXB object model the XML files are bound to is rather complex. We added mechanics to search for the nodes you want to work with. Basically, we added a class that traverses each bound node and runs a `PartialFunction` on it.

[Relevant test](https://github.com/AndreVanDelft/scalaxb/commit/ead4e9dfe6c3e73784052866818900a9c8806e49)

### Relevant commits
- [Template](https://github.com/AndreVanDelft/scalaxb/commit/733583ead2347d9c699dfc8048454afcdabcfc5c)
- [Template generation](https://github.com/AndreVanDelft/scalaxb/commit/2400b20e3994b5b0c0d763c9c4aeadaf10afee06)

## Automatic package names generation based on the namespace URI
If you want to keep large projects, like OpenOffice schemata, organized and don't want to enter a dozen package names by hand, this features is a must. An `--autopackages` flag will assign each scala file a package based on its schema URI, see [here](https://github.com/AndreVanDelft/scalaxb/compare/2dcfab944b54e5bfbfeb873bc47813f827f2e97e...86722464c32215a9210bf42970a8f36fa62f3f78#diff-463986168bc90d84f31bc1c32d546de3R222) how.

[Relevant test](https://github.com/AndreVanDelft/scalaxb/commit/daee762692976abb025570e9406cc9444257b31e)

### Relevant commits
- [Feature added](https://github.com/AndreVanDelft/scalaxb/compare/2dcfab944b54e5bfbfeb873bc47813f827f2e97e...86722464c32215a9210bf42970a8f36fa62f3f78)
- [Drop](https://github.com/AndreVanDelft/scalaxb/commit/23b0f96709e050fb2d2d817b99ef23e9c2638130) the `http` part of the URI during package name generation, since it is the same for the majority of the schemata anyway

## Deployment script
Standard deployment procedure requires Conscript and is a bit complicated. For some cases, it is easier to just generate a jar and an executable. We have added a shell script that does just that. If you run `./deploy.sh` from the root of the project, you'll have a jar and an executable under `install/` directory.

[Relevant commit](https://github.com/AndreVanDelft/scalaxb/commit/ff15c4b057e5de4a00c4be46a47678cdb3017122)

# Bug fixes
## Name clashes in `protocol.xml`
Consider OpenOffice schemata, files `dml-main.xsd` and `sml.xsd`. Both define `<xsd:complexType name="CT_Table">`. When generating them in different packages, `protocol.scala` generates classes with identical names for both of these types.

This is due to the following code in the `compiler/xsd/Lookup.scala`:

```scala
  def buildFormatterName(namespace: Option[String], name: String): String = {
    val pkg = packageName(namespace, context) getOrElse {""}
    val lastPart = pkg.split('.').reverse.head
    
    lastPart.capitalize + name + "Format"
  }
```

So if the package names have the identical last part, there will be a clash.

Since `protocol.scala` is not supposed to be used directly by the end user and is needed only for the implicits, we decided to use the entire package name to construct these class names. This way, they are much longer, but unambiguous.

[Relevant commits](https://github.com/AndreVanDelft/scalaxb/compare/86722464c32215a9210bf42970a8f36fa62f3f78...6a35275c555f0182bbde43761ac8f1f3aec15ad4)

## Name clashes between enum value bindings and Scala predef values
Consider this snippet from OpenOffice's `sml.xsd`:

```xml
  <xsd:simpleType name="ST_DdeValueType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="nil"/>
      <xsd:enumeration value="b"/>
      <xsd:enumeration value="n"/>
      <xsd:enumeration value="e"/>
      <xsd:enumeration value="str"/>
    </xsd:restriction>
  </xsd:simpleType>
```

On line 3, the enum binding object for that value will be named Nil, which clashes with Scala's predefined Nil. We fixed that by prefixing the object name with "EnumValue_" if this name clashes with a Scala keyword or a commonly used name.

[Relevant commit](https://github.com/AndreVanDelft/scalaxb/commit/5899995bef56665ac66738f379b7029b9de315ec)

Some previous work to fix that, undone by the mentioned commit:

- [This](https://github.com/AndreVanDelft/scalaxb/commit/35568727de05ddf3668cac8c57794f2f4aa78aa1)
- [This](https://github.com/AndreVanDelft/scalaxb/commit/7643c622cc48a93804db110a2d3a80a7d492ee3e)
- [This](https://github.com/AndreVanDelft/scalaxb/commit/bc04fc982fe488f99b8c399a4be177c9f02393bd)

## Data types are taken into account for Enums
Consider the following snippet from `dml-main.xsd`:

```xml
  <xsd:simpleType name="ST_PitchFamily">
   <xsd:restriction base="xsd:byte">
     <xsd:enumeration value="00"/>
     <xsd:enumeration value="01"/>
     <xsd:enumeration value="02"/>
     <xsd:enumeration value="16"/>
     <xsd:enumeration value="17"/>
     <xsd:enumeration value="18"/>
     <xsd:enumeration value="32"/>
     <xsd:enumeration value="33"/>
     <xsd:enumeration value="34"/>
     <xsd:enumeration value="48"/>
     <xsd:enumeration value="49"/>
     <xsd:enumeration value="50"/>
     <xsd:enumeration value="64"/>
     <xsd:enumeration value="65"/>
     <xsd:enumeration value="66"/>
     <xsd:enumeration value="80"/>
     <xsd:enumeration value="81"/>
     <xsd:enumeration value="82"/>
   </xsd:restriction>
   </xsd:simpleType>
   
   <!-- ... -->
<xsd:attribute name="pitchFamily" type="ST_PitchFamily" use="optional" default="0"/>
```

Lines of interest are 3 and 25. The type of `ST_PitchFamily` is `byte`, so it is reasonable to expect `00` and `0` to be the same value. But in ScalaXB, `0` will throw an exception when you try to convert it to `ST_PitchFamily`, since ScalaXB treats all its enum values as strings.

After our changes, the code generated for `ST_PitchFamily` is this:

```scala
object ST_PitchFamily {
  def fromString(value: String, scope: scala.xml.NamespaceBinding): ST_PitchFamily = scalaxb.fromXML[Byte](scala.xml.Text(value)) match {
    case x: Byte if x == scalaxb.fromXML[Byte](scala.xml.Text("00")) => Number00
    case x: Byte if x == scalaxb.fromXML[Byte](scala.xml.Text("01")) => Number01
	// ... and so on
  }
}
```

That is, we convert the passed `value` string to the type declared in the enum, `Byte` in this case. And all the predefined enum values are also converted to this type. And the results of the conversion are compared. `00` and `0` are both converted to a `Byte` `0`, so everything works.

Previously, if I recall correctly, the code above was something like this:

```scala
object ST_PitchFamily {
  def fromString(value: String, scope: scala.xml.NamespaceBinding): ST_PitchFamily = value match {
    case "00" => Number00
    case "01" => Number01
	// ... and so on
  }
}
```

That obviously didn't work with "0".

[Relevant test](https://github.com/AndreVanDelft/scalaxb/commit/b5017139e39ffd9c5b0f79eff4db2e84be07edca)

[Relevant commit](https://github.com/AndreVanDelft/scalaxb/commit/055d75044255bcbe280f60db454b1d7644b6204a)

## Protocol package is always guaranteed to be set
See issue #382. Protocol package can't be empty, since protocol is generated as "object `package`". It is reasonable that it should always be defined.

Previously, if no packages were specified by the user, the protocol was generated without a package. If some packages were specified by the user, but not for the protocol, the protocol occupied some package from the list specified by the user. This is a counterintuitive behaviour, since the protocol has the entities for all the packages, so its own package must be something more global.

We made the protocol to always have a meaningful package name. The package name selection goes as follows:

1. If `--protocol-package` is set, use it
2. Else, if `-p`, (`--default-package`) is set, use it (i.e. use the default package name)
3. Else, use a reasonable default - `scalaxb.package`

[Relevant commits](https://github.com/AndreVanDelft/scalaxb/compare/97b1939b0c6cf4a1dac51d6c9053484a3f83ff0a...2456f5d839aa08c5fbe6046a20a1b6e20ae6ad7d)

## Tests are executed sequentially
In process of their work, test examples generate files to `tmp/` directory. Specs2 executes them in parallel by default, so they write to that directory at the same time. It was OK (more or less), since the tests apparently use different package names and the templates are the same for each test.

Since `scalaxb.scala.template` now has the placeholder for the name of the protocol package in its code, sharing this file between the examples is no longer possible. Moreover, writing this file in parallel for different examples pumps some junk at the end of that file, preventing it from compiling successfuly.

We have disabled the parallel execution of the test examples for that reason, we did not experience any disastrous performance drops because of it.

### Relevant commits
- [Feature](https://github.com/AndreVanDelft/scalaxb/compare/2eb4a0c2ef05bcfcdccfc00673db5b746dae5326...587381ec3b361cb29b5bbb05aa5a1647cec98a55)
- [Fix of the bug introduced by the feature](https://github.com/AndreVanDelft/scalaxb/commit/e58fdcc608b6b9a2783802a67ccf57f85738dd14)

### CODE REVIEW

**Comment by eed3si9n** [comment]
wow. Looks like you've put in a lot of time hacking on scalaxb.
I'd like to incorporate as much as I can from your work, but I also want to make sure I understand each pieces as I'd have to maintain them afterwards. Could we perhaps split thing into multiple pull requests of bug fixes and then discuss some other features and refactorings?

**Comment by anatoliykmetyuk** [comment]
I'm not sure about splitting the stuff into multiple pull requests. It seems that it is only possible to send a pull request of commits in chronological order. That is, I can only send a range of commits starting from the first commit you don't have and ending with some later commit.

For example, the first 3 commits we have refactor the layout of some sources. After these, we have a bunch of commits for the `--mutable` flag, for the `deploy.sh` deployment script and automatic package names generation. They are intertwined one with another in no particular order. Moreover, most of our early commits are work-in-progress, they are mostly discarded by the later commits. Bug fixes follow a bit later, and the tests for all the features and bugs are added at the latest commits.

Is there any way to send a pull request with a more custom range of commits? Or any other solution to split the things in a logical way?

**Comment by anatoliykmetyuk** [comment]
Ok, seems I figured out how to split the work.

I'll do `git diff` between your master and our master, produce separate diffs from this diff, one for each bug/feature, then create a separate branch for each bug/feature, fill it with `git apply` of the patch. Then I'll send a pull request for each branch separately.

If you know a better strategy, please let me know.

**Comment by eed3si9n** [comment]
@anatoliykmetyuk I have limited experience using it, but I think [git rebase](https://git-scm.com/docs/git-rebase) has interactive mode that can be used to split/squash things.

**Comment by eed3si9n** [comment]
Did we get all the changes merged from here?
I would like to thank you both for the fixes and enhancements. Are there a company or projects I should also thank in the release note?

**Comment by anatoliykmetyuk** [comment]
>Did we get all the changes merged from here?

All the features and bug fixes. There is only a refactoring of layout left, for instance [this](https://github.com/AndreVanDelft/scalaxb/blob/master/cli/src/main/scala/scalaxb/compiler/Config.scala) looks much cleaner to read than [this](https://github.com/eed3si9n/scalaxb/blob/master/cli/src/main/scala/scalaxb/compiler/Config.scala). If you're interested, I can make a PR for that too.

>I would like to thank you both for the fixes and enhancements. Are there a company or projects I should also thank in the release note?

We're happy to help. I guess no, there's only two of us doing trying to build an app with ScalaXB.

**Pull request closed without merging**
