### PR TITLE
Fix test compilation issues introduced in PR #407

### PR DESCRIPTION
**Pull request by hosamaly**
PR #407 was originally created in 2016. It was merged a few days ago
but it needed to be updated to match the new code.

### CODE REVIEW

**Comment by eed3si9n** [comment]
Thanks so much!

**Comment by hosamaly** [comment]
You're welcome. :)

**Comment by hosamaly** [comment]
May I ask you a question about the Travis config, please? Why does it execute `sbt integration/test`? Is there a reason not to run `sbt test` on the root project? I'd assume that the latter would run the sbt plugin tests, wouldn't it?

**Comment by eed3si9n** [comment]
I think it's because the scripted tests need to run for the Scala version sbt uses.

**Comment by hosamaly** [comment]
The build server is showing a test failure that I'm unable to reproduce locally! :(
> [info] Wsdl11Soap12AsyncTest
> [info] ! stockquote.scala file must compile
> [error]  RuntimeException: : Error interpreting
> ```scala
> val service = (new stockquote.StockQuoteSoap12Bindings with scalaxb.SoapClientsAsync with scalaxb.DispatchHttpClientsAsync with scalaxb.GlobalExecutionContextProvider {}).service
> val fresponse = service.getQuote(Some("GOOG"))
> val response = Await.result(fresponse, 5.seconds)
> ```
>  (CompilerMatcher.scala:102)
> [error] CompilerMatcher$$anon$2.$anonfun$apply$2(CompilerMatcher.scala:102)
> [error] CompilerMatcher$$anon$2.$anonfun$apply$2$adapted(CompilerMatcher.scala:101)
> [error] CompilerMatcher$$anon$2.apply(CompilerMatcher.scala:101)
> [error] Wsdl11Soap12AsyncTest$.$anonfun$new$1(Wsdl11Soap12AsyncTest.scala:24)
Have you seen something like this before?

I'm inclined to swap the order of mixing the traits `scalaxb.DispatchHttpClientsAsync` and `scalaxb.GlobalExecutionContextProvider`. Unfortunately, since I can't reproduce the failure locally, I'd have to rely on Travis CI to check it!

**Comment by eed3si9n** [comment]
It's using external web service, so that the error might be transient or throttled.
Let me restart it.

**Comment by hosamaly** [comment]
Thanks. Looks like it has passed now.

**Pull request merged**
