### PR TITLE
Ability to ignore unknown elements in response

### PR DESCRIPTION
**Pull request by jet-black**
Our team wants scalaxb to be able to ignore unknown xml elements inside response, as well as ignoring order in which they are arrived. It is against XSD specification, but it is very useful when another server changes it's schema without notifying clients. Please, review this request.

### CODE REVIEW

**Comment by eed3si9n** [comment]
I have a few minor comments, but overall this looks like a really nice addition to scalaxb.
Thanks a lot!

**Comment by jet-black** [comment]
Ok, I've resolved conflicts. We've made some load testing on that feature. Also we are already using this feature in production under highload, so the changes are working fine without any errors.

**Comment by eed3si9n** [comment]
I can no longer see whatever I commented, but thanks for the update.
I am guessing one of them is that it fixes #291/#298, which should be noted in the release note.

**Comment by jet-black** [comment]
I've made updates for notes, please, review.

**Pull request merged**
