### PR TITLE
http4s client + tagless final style generation

### PR DESCRIPTION
**Pull request by zarthross**
# What this PR Does:

- Add support for tagless style service generation.
- Add an http4s client with support for 0.21 and 0.23 (I needed these 2, but I could be convinced to add others)

# TODO

- [x] Manually Test CLI client
- [x] Add maven params for new cli arguments
- [x] Resolve conflicts
~- [ ] Update Docs~ (I'll do this if you tell me how 😆 )

### CODE REVIEW

**Review by eed3si9n — APPROVED** [review]
Thanks @zarthross!

**Comment by zarthross** [comment]
@eed3si9n No rush, but do you have an idea on when you might merge and release this change?  I'm trying to determine if I need to cut an internal release or not in order to use this feature and knowing what your expected timeline is could save me some time 😄

**Comment by eed3si9n** [comment]
I'll try to release today or tomorrow.

**Comment by eed3si9n** [comment]
So I released 1.10.0, but it doesn't seem to generate http4s client when I set to the following:

```scala
import Dependencies._

ThisBuild / organization  := "com.example"
ThisBuild / version := "0.1.0-SNAPSHOT"
ThisBuild / scalaVersion := "2.13.10"

lazy val scalaXml = "org.scala-lang.modules" %% "scala-xml" % "1.3.0"
lazy val scalaParser = "org.scala-lang.modules" %% "scala-parser-combinators" % "1.1.2"
lazy val jaxbApi = "javax.xml.bind" % "jaxb-api" % "2.3.0"

lazy val root = (project in file("."))
  .enablePlugins(ScalaxbPlugin)
  .settings(
    name := "soap",
    libraryDependencies ++= Seq(scalaXml, scalaParser, jaxbApi),
    Compile / scalaxb / scalaxbPackageName := "generated",
    Compile / scalaxb / scalaxbGenerateDispatchClient := false,
    Compile / scalaxb / scalaxbGenerateHttp4sClient := true,
  )

```

**Comment by zarthross** [comment]
Thanks for releasing it!!!

Looks like I missed an edge case, you need to explicitly set the `scalaxbHttpClientStyle` to `tagless` in order for it to work.  If you like I can do a follow up PR to fix that.

```scala
scalaxbHttpClientStyle  := HttpClientStyle.Tagless,
```

**Comment by eed3si9n** [comment]
Here's how I followed up - https://github.com/eed3si9n/scalaxb/pull/597

**Pull request merged**
