### PR TITLE
Add support for Gigahorse http library.

### PR DESCRIPTION
**Pull request by alexdupre**
I've kept dispatch as default. I'm not sure if we prefer that `scalaxbGenerateGigahorseClient` automatically disable the dispatch client; currently it doesn't, so you have to set `scalaxbGenerateDispatchClient := false` and `scalaxbGenerateGigahorseClient := true` to generate the Gigahorse clients.

### CODE REVIEW

**Comment by eed3si9n** [comment]
wow. Thank you very much for this! Instead of Booleans what do you think about defining sealed trait `HttpClientType` or something like that?

**Comment by gabro** [comment]
Cool! Does this enable supporting scala 2.12 as per #408?

**Comment by gabro** [comment]
@alexdupre 🎉 wonderful, thanks!

**Comment by alexdupre** [comment]
@eed3si9n: would you prefer to replace `scalaxbGenerateDispatchClient`, `scalaxbGenerateDispatchAs`, `scalaxbGenerateGigahorseClient` (or just dispatch/gigaorse client) with a single key of `HttpClientType`? Or such additional key, if set, would set the value of other three?

**Comment by eed3si9n** [comment]
I think for backward compatibility we should keep any existing keys, so the second option I think would be better.

**Comment by alexdupre** [comment]
I'm about to push a commit for it that simplifies the sbt setting for a single client, but I'm sure you have much more knowledge on sbt, so feel free to replace it completely as you prefer.

**Pull request merged**
