### PR TITLE
Add useVarArgs option in mvn-scalaxb

### PR DESCRIPTION
**Pull request by Erwan56**
This pull request is linked to the following one https://github.com/eed3si9n/scalaxb/pull/292. It allows maven users to configure useVarArgs option.

### CODE REVIEW

**Comment by lbruand** [comment]
:+1: 
Hello,

This would be super useful for us.

Thanks,
Lucas

**Comment by eed3si9n** [comment]
I just merged it but `use-varargs` doesn't make sense if that's the default value. We need `no-varargs` as `Unit` flag. I can fix this myself.

**Comment by Erwan56** [comment]
Ok. That means that you reverse the option
use-varargs = false  < = >  no-varargs = true

Sounds good.

**Pull request merged**
