### PR TITLE
Adds TimeoutTest

### PR DESCRIPTION
**Pull request by eed3si9n**
This is in response to @joescii's post [Configuring timeout for scalaxb][1].

## TimeoutTest

1. The test creates an Apache CXF SOAP service with fake `Thread.sleep` set to 3s to emulate a slightly-long-running process.
2. The test bakes a special cake based on Joe's implementation. (I might actually make this the default impl) This introduces configurable timeouts set to 10s by default. Overridden to be 1s for the test.
3. Future#failed projection is called to flip the success/failure state.
4. The test awaits 10s for the client and server to play its course.

The test seems to be returning `ExecutionException` as expected.

  [1]: https://groups.google.com/d/msg/scalaxb/dGKLXNpmZ88/aBMTtwuDK8UJ

### CODE REVIEW

**Comment by joescii** [comment]
I grabbed this branch so I could run the tests locally.  After publishing the `app` project locally, I switched to the `integration` project and ran `test`.  It erupted with scalac sadness.

```text
[init] error: error while loading Object, Missing dependency 'object scala in compiler mirror', required by C:\Program Files\Java\jdk1.8.0_25\jre\lib\rt.jar(java/lang/Object.class)

Failed to initialize compiler: object scala in compiler mirror not found.
** Note that as of 2.8 scala does not assume use of the java classpath.
** For the old behavior pass -usejavacp to scala, or if using a Settings
** object programatically, settings.usejavacp.value = true.
[info] CrossNamespaceTest
[info] ! xn.scala must compile so that CrossNamespaceChoice can be used
[error]  MissingRequirementError: : object scala in compiler mirror not found.  (CompilerMatcher.scala:79)
[error] CompilerMatcher$$anon$2.apply(CompilerMatcher.scala:79)
[error] CrossNamespaceTest$$anonfun$1.apply(CrossNamespaceTest.scala:19)
[error] CrossNamespaceTest$$anonfun$1.apply(CrossNamespaceTest.scala:19)
```

I tried out the suggestion of using `-Dsettings.usejavacp.value=true`.  The problems are different but still present.

```text
[info] CrossNamespaceTest
[info] ! xn.scala must compile so that CrossNamespaceChoice can be used
[error]  FatalError: : package scala does not have a member Int  (CompilerMatcher.scala:79)
[error] CompilerMatcher$$anon$2.apply(CompilerMatcher.scala:79)
[error] CrossNamespaceTest$$anonfun$1.apply(CrossNamespaceTest.scala:19)
[error] CrossNamespaceTest$$anonfun$1.apply(CrossNamespaceTest.scala:19)
```

I've yet to google anything helpful here.  Do you have any initial thoughts regarding what I may be missing in my environment setup?

**Comment by eed3si9n** [comment]
Works for me.

```
$ sbt
...
root> project integration
integration> scalaVersion
[info] 2.11.4
integration> testOnly TimeoutTest
```

**Comment by joescii** [comment]
That's because you're the _sbt Whisperer_...

Early on I suspected my bastardized Windows platform.  I should have pursued that more.  I stumbled across [this comment](https://github.com/scoverage/scalac-scoverage-plugin/issues/83#issuecomment-72456412) this morning, leading me back to that well.  I hacked up something that got me further.  I'll let you know what I come up with later today.

**Comment by joescii** [comment]
I got straightened out in [PR307](https://github.com/eed3si9n/scalaxb/pull/307).  I confirmed what I needed to know, which is we can set the timeouts higher than the defaults.  The branch is [here](https://github.com/joescii/scalaxb/tree/longer-timeout), if you're the least bit interested.

**Comment by eed3si9n** [comment]
Thanks for #307.
So the timeout generally works with scalaxb + Dispatch combo?
I've been thinking if people find it useful, I can make timeout client the default implementation. WDYT?

**Comment by joescii** [comment]
Yes, the timeouts seem to work without any problems.  

I think it's a good call to go with the timeout client.  It took me a good bit of digging to figure out how to do it, considering scalaxb, dispatch, async-http, and netty are all (potentially) involved.  It shouldn't hurt anything as long as the values are the same as the defaults.

**Pull request merged**
