### PR TITLE
Deploy script

### PR DESCRIPTION
**Pull request by anatoliykmetyuk**
A `deploy.sh` script to conveniently install the command-line application without Conscript. Upon running `./deploy.sh`, two files will be created under `install/` directory: the jar with the application and all the dependencies and an executable to run this jar.

### CODE REVIEW

**Comment by eed3si9n** [comment]
I feel like this could be expressed using build.sbt.
I could merge this as is and fix it up myself.

**Comment by anatoliykmetyuk** [comment]
I googled a bit and found this [answer](http://stackoverflow.com/a/25005651/3895471) describing how to execute shell commands from build.sbt. Did you mean this, or some other solution? I can apply it myself. I often follow this deployment pattern with a script, so it would be interesting to learn a technique without it.

**Comment by anatoliykmetyuk** [comment]
Ok, got it, the Assembly plugin already has such a functionality. The build can go using `sbt app/assembly`. Nice, didn't know about it! Is there any way to avoid using `assemblyJarName` [here](https://github.com/eed3si9n/scalaxb/pull/393/files#diff-fdc3abdfd754eeb24090dbd90aeec2ceR42)? I think it's reasonable to specify only a directory under `assemblyOutputPath`, since we have already specified the file name, so why repeat it? If I only specify the directory `./` in the `assemblyOutputPath`, then it gets purged when I run `app/assembly`.

**Comment by anatoliykmetyuk** [comment]
Never mind: just deleted `assemblyJarName` option all together.

**Comment by eed3si9n** [comment]
Squashed the PR as 172c052f3a15116881d5d673bdcc3fab7f2d9af6

**Pull request merged**
